### PR TITLE
Portfolio: details popup window

### PR DESCRIPTION
**Pull request by benjp009**
# 👋 Micronaut Reviewer 

[Portfolio: details popup window
](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md)

### Requirements 🚀

We have reviewed the following on the page for best accessibility : 

For this project: 
- [x] you should add the JavaScript + HTML + CSS linter.

In mobile, implement the following features:

- [x] When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- [x] When the user clicks (or taps) the close (X) button, the popup disappears.
- [x] You should implement popups for both mobile and desktop screen sizes.
- [x] You must stick to the design as much as possible
- [x] you must use a JavaScript array **to store all of the information for all projects.**
- [x] For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.
- [x] You need to update the main page so that the projects' section is created dynamically using the information stored in that JavaScript object.

### Pair Programming 🎳

For this exercise, PP was required, we worked very closely with @fabianofrank to make the best looking possible portfolio for you to review

### Additional requirements

- [ ] On desktop, when the user clicks on the "Next project" / "Previous project" buttons, they will navigate to the the next/previous project details in the popup.
- [ ] If the project is the first one, the "Previous project" button is disabled
- [ ] If the project is the last one, the "Next project" button is disabled

Happy Review :)

### CODE REVIEW

**Comment by benjp009** [comment]
## Special note 📝
All the requirements for this exercise are done, we are still working on improving the deliverability of the popup info for next required tasks 

## Special Thanks 🙏
Thanks to @fabianofrank for the assistance on the code and also to @keroloussamy & @rtonata88 for the help this morning to find out my problems on the code

**Review by ignatius22 — CHANGES_REQUESTED** [review]
## :wave:  Micronaut Reviewer
Portfolio: [details popup window](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md)

## Requirements :rocket:
We have reviewed the following on the page for best accessibility :

For this project:

- [ ] you should add the JavaScript + HTML + CSS linter. Let's ensure the linter runs properly and doesn't fail.

In mobile, implement the following features:

- [ ] When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- [ ] When the user clicks (or taps) the close (X) button, the popup disappears.
- [ ] You should implement popups for both mobile and desktop screen sizes.
- [ ] You must stick to the design as much as possible you must use a JavaScript array to store all of the information for all projects.
 For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to the source.
 - [ ] You need to update the main page so that the projects' section is created dynamically using the information stored in that JavaScript object.

## Pair Programming :bowling:
For this exercise, PP was required, we worked very closely with @fabianofrank to make the best looking possible interaction of the mobile menu for my portfolio.

## Additional requirements
 - [ ] On desktop, when the user clicks on the "Next project" / "Previous project" buttons, they will navigate to the next/previous project details in the popup.
 - [ ] If the project is the first one, the "Previous project" button is disabled.
 - [ ] If the project is the last one, the "Next project" button is disabled.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Ghiftee — APPROVED** [review]
## STATUS: APPROVED ♻️♻️
Hi @benjp009, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

**Comment by benjp009** [comment]
@Ghiftee 

###That's AMAZING NEWS ! 

## Thank you a thousand times !

**Pull request merged**
